version: '3'

services:
  curriculum:
    build:
      context: .
      target: curriculum
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

  training-management:
    build:
      context: .
      target: training-management
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: always 