version: "3.9"
services:
  frontend:
    container_name: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map port 3000 in the container to port 3000 on the host
    environment:
      # Pass environment variables to the container
      NEXT_PUBLIC_API_URL: "http://164.90.209.220:8081/api"
      NODE_ENV: "production"
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm start # Run the Next.js production server
