version: "3.9"
services:
  frontend:
    container_name: curriculum-prod-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: ["pnpm", "run", "start"]