version: "3.9"
services:
  frontend:
    container_name: curriculum-prod-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map port 3000 in the container to port 3000 on the host
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm start # Run the Next.js production server