name: Next.js CI/CD Workflow

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js (only needed if caching dependencies)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.19.1

    # Step 3: SSH Agent Setup for Deployment
    - name: SSH Agent Setup
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    # Step 4: Deploy to Dev Environment
    - name: Deploy to Dev Environment
      run: |
        ssh -v -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<'ENDSSH'
        cd frontend

        # Clone the repository if it doesn't already exist
        if [ ! -d "curriculum-services" ]; then
          git clone git@github.com:training-solution-frontend/curriculum-services.git
        fi

        # Navigate to the project directory
        cd curriculum-services

        # Pull the latest changes from the repository
        git pull 

        # Ensure Docker is running and deploy the app using Docker Compose
        docker compose -f docker-compose.prod.yml down
        docker compose -f docker-compose.prod.yml up --build -d
        docker ps

        # List running Docker containers
        docker ps
        ENDSSH
